name: Deploy React to NGINX

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js (versão 20 ou 22)
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Limpar o cache do npm
    - name: Clean npm cache
      run: npm cache clean --force

    # Instalar as dependências
    - name: Install dependencies
      run: npm install

    # Verificar dependências desatualizadas
    - name: Check outdated dependencies
      run: npm outdated

    # Rodar os testes
    - name: Run tests
      run: npm test

    # Construir o projeto
    - name: Build project
      run: npm run build

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: ./build/* # Caminho do build gerado
        target: /usr/share/nginx/html/dist # Diretório onde o NGINX serve a aplicação

    - name: Restart NGINX
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo nginx -t
          sudo systemctl restart nginx
