name: Deploy React to NGINX

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Exibir versão do Node.js
    - name: Node.js version
      run: node --version

    # Limpar o cache do npm
    - name: Clean npm cache
      run: npm cache clean --force

    # Instalar dependências e construir o projeto
    - name: Build project
      run: |
        echo "Entrando no diretório site..."
        cd site
        echo "Instalando dependências..."
        npm install
        echo "Iniciando o processo de build..."
        npm run build
        echo "Build concluído com sucesso!"

    # Verificar arquivos construídos
    - name: List build directory
      run: |
        echo "Arquivos no diretório de build:"
        ls -la ./site/dist

    # Copiar arquivos para o EC2
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: ./site/dist/* # Caminho do build gerado
        target: /usr/share/nginx/html/dist # Diretório onde o NGINX serve a aplicação

    # Verificar arquivos no EC2
    - name: Check files on EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Verificando arquivos no servidor..."
          ls -la /usr/share/nginx/html/dist

    # Reiniciar o NGINX
    - name: Restart NGINX
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Testando configuração do NGINX..."
          sudo nginx -t
          echo "Reiniciando NGINX..."
          sudo systemctl restart nginx
          echo "NGINX reiniciado com sucesso!"

    # Verificar status do NGINX
    - name: Check NGINX status
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Status do NGINX:"
          sudo systemctl status nginx | head -n 20
