name: Deploy React to NGINX

on:
  push:
    branches:
      - main # Dispara o workflow quando há push na branch "main"

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Fazer checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Etapa 2: Instalar Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0 # Substitua pela versão que sua aplicação usa

      # Etapa 3: Instalar dependências
      - name: Install Dependencies
        run: npm install

      # Etapa 4: Build da aplicação React
      - name: Build React Application
        run: npm run build

      # Etapa 5: Enviar o build para a EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./build/ # Caminho local
          target: ${{ secrets.DIST_PATH }} # Caminho no servidor

      # Etapa 6: Reiniciar o NGINX na EC2
      - name: Restart NGINX
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl restart nginx
