on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js
    - name: Set up Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Exibir versão do Node.js
    - name: Node.js version
      run: node --version

    # Limpar o cache do npm
    - name: Clean npm cache
      run: npm cache clean --force

    # Instalar dependências e construir o projeto
    - name: Build project
      run: |
        echo "Entrando no diretório site..."
        cd site
        echo "Instalando dependências..."
        npm install
        echo "Iniciando o processo de build..."
        npm run build
        echo "Build concluído com sucesso!"

    # Compactar os arquivos de build
    - name: Compress build files
      run: |
        echo "Compactando os arquivos de build..."
        tar -czf build.tar.gz -C ./site/dist .

    # Copiar os arquivos diretamente para o diretório onde o NGINX serve os arquivos
    - name: Copiar arquivos de build para o servidor EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: ./site/dist/*    # Copiar todos os arquivos da pasta dist
        target: /usr/share/nginx/html/dist/
        debug: true

    # Reiniciar o NGINX
    - name: Reiniciar o NGINX
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Testando configuração do NGINX..."
          sudo nginx -t
          echo "Reiniciando NGINX..."
          sudo systemctl restart nginx
          echo "NGINX reiniciado com sucesso!"

    # Verificar status do NGINX
    - name: Verificar status do NGINX
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Status do NGINX:"
          sudo systemctl status nginx | head -n 20
