name: Deploy React to NGINX

on:
  push:
    branches:
    - main # A ação será acionada quando você fizer push na branch 'main'
  pull_request:
    branches:
    - main # Também será acionado quando um pull request para a branch 'main' for aberto ou atualizado

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Verifique qual versão do Node.js você usa

    - name: Install Dependencies
      run: npm install

    - name: Build React Application
      run: npm run build

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: ./build/* # Caminho do build gerado
        target: /usr/share/nginx/html/dist # Diretório onde o NGINX serve a aplicação

    - name: Restart NGINX
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo nginx -t
          sudo systemctl restart nginx
